apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc }}
  username: {{ .Values.mysql.username | b64enc }}
  password: {{ .Values.mysql.password | b64enc }}
