apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-phpmyadmin
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.phpmyadmin.port }}
      targetPort: {{ .Values.phpmyadmin.port }}
  selector:
    app: {{ .Release.Name }}-phpmyadmin
